server:
  port: 5001
spring:
  application:
    name: "requestloan-credya-reactivo"
  devtools:
    add-properties: false
  #r2dbc:
   # url: r2dbc:postgresql://postgres-crediya:5432/crediyaloanrequest
   # username: mfacevedo
   # password: password
  #r2dbc:
   # url: r2dbc:postgresql://localhost:5432/crediyaloanrequest
   # username: mfacevedo
   # password: password
  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://localhost:5432/crediyaloanrequest}
    username: ${DB_USERNAME:mfacevedo}
    password: ${DB_PASSWORD:password}


    sql:
      init:
        mode: always  # en dev, para ejecutar schema.sql/data.sql si los pones
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
springdoc:
  api-docs:
    enabled: true
  webflux:
    use-management-port: false

aws:
  region: ${REGIONALS:us-east-1}
  accessKeyId: ${ACCESSORY:test}
  secretAccessKey: ${SECRETARY:test}
  queue: ${QUEUE:http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/cola-pruebas}
  sns: ${ARNTOPIC:arn:aws:sns:us-east-1:000000000000:notificaciones}
  sqsSns: ${SUBSEQUENTS:arn:aws:sns:us-east-1:000000000000:notificaciones:d768f633-b2c0-4214-99f0-3e5fe5b16e16}


cors:
  allowed-origins: "http://localhost:4200,http://localhost:5001"
